json.id movie.id
json.title movie.title
json.year movie.year
json.plot movie.plot
json.english movie.english
json.director movie.director 
json.message {Actor}
json.first_name actor.first_name 
json.last_name actor.last_name 
json.gender actor.gender 
json.age actor.age 
